# Generated by Django 5.2.6 on 2025-10-03 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UpgradeOption",
        ),
    ]
