# Generated by Django 5.2.6 on 2025-09-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="profile_picture",
            field=models.ImageField(
                default="profile_pics/default.png", upload_to="profile_pics/"
            ),
        ),
    ]
