# Generated by Django 5.2.6 on 2025-11-03 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_studentprofile_department_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Announcement",
        ),
    ]
